# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 01:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20170505_2047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='rol',
        ),
        migrations.AddField(
            model_name='user',
            name='example',
            field=models.CharField(default='a', max_length=200),
            preserve_default=False,
        ),
    ]
