# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 02:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20170505_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='example',
        ),
        migrations.AddField(
            model_name='myuser',
            name='rol',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='user_rol', to='account.Rol'),
            preserve_default=False,
        ),
    ]
