# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 22:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colegio', '0003_auto_20170508_1634'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('idEstudiante', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('colegio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colegio.Colegio')),
            ],
        ),
    ]
