# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0002_auto_20170513_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentosVehiculo',
            fields=[
                ('idDocumentosVehiculo', models.IntegerField(primary_key=True, serialize=False)),
                ('tipoVehiculo', models.CharField(max_length=50)),
                ('fechaExpedicion', models.CharField(max_length=10)),
                ('fechaVencimiento', models.CharField(max_length=10)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.Vehiculo')),
            ],
        ),
    ]
