# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentosVehiculo', '0002_auto_20170514_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosvehiculo',
            name='fechaExpedicion',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='documentosvehiculo',
            name='fechaVencimiento',
            field=models.DateField(),
        ),
    ]
