# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentosVehiculo', '0003_auto_20170514_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentosvehiculo',
            name='idDocumentosVehiculo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
