# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('idColegio', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('nit', models.CharField(max_length=10)),
            ],
        ),
    ]
