# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colegio', '0002_auto_20170508_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegio',
            name='direccion',
            field=models.CharField(max_length=100),
        ),
    ]
