# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 03:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20170508_0354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='lat_end',
            new_name='lat_start',
        ),
    ]
