# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-21 17:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0004_device_trace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trace',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
