# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-14 00:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conductor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('idVehiculo', models.IntegerField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=10)),
                ('marca', models.CharField(max_length=20)),
                ('linea', models.CharField(max_length=20)),
                ('modelo', models.IntegerField()),
                ('cilindraje', models.IntegerField()),
                ('color', models.CharField(max_length=20)),
                ('clase', models.CharField(max_length=20)),
                ('tipo', models.CharField(max_length=20)),
                ('serie', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=20)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conductor.Conductor')),
            ],
        ),
    ]
